import {lazy} from 'react';

export const CoursePopup =  lazy(()=>import('./course'))
export const MoveItem =  lazy(()=>import('./move_item'))
export const MoveSeat =  lazy(()=>import('./move_seat'))
export const AddNote =  lazy(()=>import('./notes'))
export const Search =  lazy(()=>import('./search'))
export const Void =  lazy(()=>import('./void'))
export const Fire =  lazy(()=>import('./fire'))
export const FireTime =  lazy(()=>import('./fire_time'))
export const FireAt =  lazy(()=>import('./fire_at'))
export const FireItem =  lazy(()=>import('./fire_item'))
export const SharedOrder =  lazy(()=>import('./shared_order'))
export const PrintOrder =  lazy(()=>import('./print_order'))
export const TablePopup =  lazy(()=>import('./table'))
export const EditTable =  lazy(()=>import('./edit_table'))
export const AddTable =  lazy(()=>import('./add_table'))
export const PlaceTable =  lazy(()=>import('./place_table'))
export const EditTableAdmin =  lazy(()=>import('./edit_table_admin'))
export const TransferTable =  lazy(()=>import('./transfer_table'))
export const CombineTable =  lazy(()=>import('./combine_table'))
export const AssignCustomer =  lazy(()=>import('./assign_customer'))

export const ShareItem =  lazy(()=>import('./share_item'))
export const EditShare =  lazy(()=>import('./edit_share'))
export const Receipt =  lazy(()=>import('./receipt'))
export const DatePickerPopup =  lazy(()=>import('./datePicker'))
export const HoldOrder =  lazy(()=>import('./hold_order'))
export const PayReceipt =  lazy(()=>import('./pay_dinin'))
export const CancelCustomer =  lazy(()=>import('./cancel_customer'))
export const ModifierQtn =  lazy(()=>import('./modifiers_qtn'))

export const Save =  lazy(()=>import('./successfully_save'))
export const Note =  lazy(()=>import('./note'))
export const DataSelector =  lazy(()=>import('./date_selector'))
export const ItemInfo =  lazy(()=>import('./item_info'))
export const QtyRefund =  lazy(()=>import('./qty_item_refund'))
export const OrderView =  lazy(()=>import('./order_view'))
export const CustOrOrgan =  lazy(()=>import('./customer_organization'))
export const RefundOrder =  lazy(()=>import('./refund_order'))
export const AssignReservation =  lazy(()=>import('./assign_reservations'))
export const CashierInfo =  lazy(()=>import('./cashier_info'))
export const Complimentary =  lazy(()=>import('./comp'))
export const SplitOrder =  lazy(()=>import('./split_order'))
export const RefundItem =  lazy(()=>import('./refund_item'))
export const AssignAllTables =  lazy(()=>import('./assign_all_tables'))
export const CheckIn =  lazy(()=>import('./check_in_addg'))
export const SeperateTable =  lazy(()=>import('./seperateTable'))
export const ReprintReceipt =  lazy(()=>import('./reprint_order'))
export const EnterNum =  lazy(()=>import('./enter_number'))
export const SetMenu =  lazy(()=>import('./set_event_menu'))
export const Information =  lazy(()=>import('./information'))
export const AddNewAddress =  lazy(()=>import('./add_new_address'))
export const ModifiersAlert =  lazy(()=>import('./modifiers_alert'))
export const No =  lazy(()=>import('./no'))
export const Doneness =  lazy(()=>import('./doneness'))
export const AddWithSelect =  lazy(()=>import('./add_wiz_select'))
export const SplitPacking = lazy(() => import('./split_packing'))
export const CallCenterPay = lazy(() => import('./call_center_pay'))
export const OrderType = lazy(() => import('./order_type'))
export const Choose = lazy(() => import('./order_type/choose'))
// export const OrderTypeSP = lazy(() => import('./order_type_sp'))
export const ChooseSP = lazy(() => import('./order_type_sp/choose'))
export const OrdersSearch = lazy(() => import('./orders_search'))
export const ServiceProvider = lazy(() => import('./service_provider'))
export const ChooseOne = lazy(() => import('./choose_one'))
export const Location = lazy(()=> import('./location'))
export const SelectOnly = lazy(()=> import('./only_select'))
export const Campaign = lazy(()=> import('./campaign'))
export const lang = lazy(()=>(import('./lang'))) 
export const ModifQuantity = lazy(()=>(import('./modif_quantity'))) 
