export const CHILED_ACTION1 = "CHILED_ACTION1";
export const GET_TYPES = "GET_TYPES";
export const SET_CURRENT_TYPE = "SET_CURRENT_TYPE";
export const SET_CURRENT_GROUP = "SET_CURRENT_GROUP";
export const SET_CURRENT_ORDER_ITEM = "SET_CURRENT_ORDER_ITEM";
export const SALES_ITEMS = "SALES_ITEMS";
export const SET_ITEM_COLOR = "SET_ITEM_COLOR";




//bill actions
export const ADD_BILL_ITEM = "ADD_BILL_ITEM";
export const REMOVE_BILL_ITEM = "REMOVE_BILL_ITEM";
export const CANCEL_ORDER = "CANCEL_ORDER";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const OPEN_QUANTITY = "OPEN_QUANTITY";
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export const SET_PAYMENT_VALUE = "SET_PAYMENT_VALUE";
export const SHOW_POPUP = "SHOW_POPUP";
export const ACTIVATE_PAY = "ACTIVATE_PAY";
export const SET_CURRENT_SEAT = "SET_CURRENT_SEAT";
export const HOLDORDER_TO_BILL = "HOLDORDER_TO_BILL";
export const LASTINDEX_CHANGE_QUINTITY = "LASTINDEX_CHANGE_QUINTITY";
export const HANDEL_CALCULATORT_QUANTITY = "HANDEL_CALCULATORT_QUANTITY";
export const SET_CURRENT_TABLE = 'SET_CURRENT_TABLE'
export const SET_CURRENT_TABLE_ORDERS = "SET_CURRENT_TABLE_ORDERS"
export const SET_DISCOUNT_TYPE = 'SET_DISCOUNT_TYPE'
export const ADD_MODIFIERS_TO_ITEM ='ADD_MODIFIERS_TO_ITEM'
export const DELETE_MODIFIER_FROM_ITEM = "DELETE_MODIFIER_FROM_ITEM"
export const SET_MOVE_SEAT = 'SET_MOVE_SEAT'
export const SET_COURSE = "SET_COURSE"
export const CHANGE_ITEM_COURSE = "CHANGE_ITEM_COURSE"
export const ADD_ACTIVE_ORDER = "ADD_ACTIVE_ORDER"
export const SET_CURRENT_ORDER = "SET_CURRENT_ORDER"
export const SET_TAXES = "SET_TAXES"
export const SET_SERVICE = "SET_SERVICE"

///Modifier 

export const SET_CURRENT_MODIFIER = "SET_CURRENT_MODIFIER";
export const CHANGE_EDIT_BTN = "CHANGE_EDIT_BTN";



//FLOOR PLANNER 

export const SET_CURRENT_SHAPE = "SET_CURRENT_SHAPE";
export const ADD_NEW_TABLE = "ADD_NEW_TABLE";
export const CLEAR_NEW_TABLES = "CLEAR_NEW_TABLES";
export const SET_CURRENT_ZONE = "SET_CURRENT_ZONE";
export const DELETE_TABLE = "DELETE_TABLE";
export const REMOVE_TABLE = "REMOVE_TABLE";

export const ALTER_TABLE_STATUS = "ALTER_TABLE_STATUS";
export const SET_DRAWAREA = "SET_DRAWAREA"
export const SET_LAST_TABLE = " SET_LAST_TABLE";






//application
export const CHANGE_MOOD = "CHANGE_MOOD";
export const UPDATE_TABLES = "UPDATE_TABLES";
export const REPLACE_CUSTOM_MENU = "REPLACE_CUSTOM_MENU";
export const REPLACE_BASE_SALESCAT = "REPLACE_BASE_SALESCAT";
export const CHANGE_BUSINESS_DAY = "CHANGE_BUSINESS_DAY";
export const CHANGE_SHIFT = "CHANGE_SHIFT";


//customer
export const CUSTOMER_ACTION = "CUSTOMER_ACTION";
export const UPDATE_TABLE_DATA = "UPDATE_TABLE_DATA";
export const SET_CURRENT_PAYMENT = "SET_CURRENT_PAYMENT";
export const APPEND_ACTIVE_ORDER = "APPEND_ACTIVE_ORDER";








