export const Fetch = (params, onSuccess, extra={}) => ({ type: "Fetching", params, onSuccess, ...extra})
export const Create = (data, onSuccess, extra={}, app=data.app)=>({type: "Creating", app, data, onSuccess, ...extra})
export const CreateBulk = (data, onSuccess, extra={}, app=data.app)=>({type: "CreatingBulk", app, data, onSuccess, ...extra})
export const Update = (data, onSuccess, extra={}, app=data.app)=>({type: "Updating", app, data, onSuccess, ...extra})
export const UpdateBulk = (data, onSuccess, extra={}, app=data.app)=>({type: "UpdatingBulk", app, data, onSuccess, ...extra})
export const UpdateMany=(data, onSuccess, extra={}, app=data.app)=>({type:'UpdatingMany',data, onSuccess, ...extra})
export const Delete = (data, onSuccess, extra={}, app=data.app)=>({type: "Deleting", app, data, onSuccess, ...extra})
export const DeleteMany = (data, onSuccess, extra={}, app=data.app)=>({type: "DeletingMany", app, data, onSuccess, ...extra})
export const FetchAll = (apps, onSuccess, extra={}) => ({ type: "FetchingAll", apps, onSuccess, ...extra})
export const SetMain = (data)=>({type: "set_main", data})
export const SetPath = (path, data)=>({type: "set_path", path, data})
export const AppendPath = (path, data)=>({type: "append_path", path, data})
export const Remove = (data)=>({type: "remove_main", data})
